/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    tutorialSidebar: [
        'resources',
        {
            type: 'category',
            label: '2026 Workshops',
            collapsed: false,
            items: [
                {
                    type: 'category',
                    label: 'Hackathon 101',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Hackathon 101' }],
                },
                {
                    type: 'category',
                    label: 'DevDay (Full Stack Project)',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Webapp-Setup' }],
                },
                {
                    type: 'category',
                    label: 'Agents and Tools',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Agents and Tools' }],
                },
                {
                    type: 'category',
                    label: 'RAG',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/RAG' }],
                },
                {
                    type: 'category',
                    label: 'Vibe Coding',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Vibe Coding' }],
                },
                {
                    type: 'category',
                    label: 'MongoDB',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/MongoDB' }],
                },
                {
                    type: 'category',
                    label: 'Pitching',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Pitching' }],
                },
            ],
        },
        {
            type: 'category',
            label: 'Past Workshops',
            collapsed: true,
            items: [
                {
                    type: 'category',
                    label: 'Github',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Github' }],
                },
                {
                    type: 'category',
                    label: 'React',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/React' }],
                },
                {
                    type: 'category',
                    label: 'Firebase',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Firebase' }],
                },
                {
                    type: 'category',
                    label: 'Advanced Styling',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Advanced Styling' }],
                },
                {
                    type: 'category',
                    label: 'Computer Vision',
                    items: [{ type: 'autogenerated', dirName: 'Workshops/Computer Vision' }],
                },
            ],
        },
    ],
};

module.exports = sidebars;
