// sidebars-dayof.js - Updated with clean titles

module.exports = {
    dayOfSidebar: [
        {
            type: 'category',
            label: 'HackUTD 2025: Lost in the Pages',
            link: {
                type: 'doc',
                id: 'index',
            },
            items: [
                {
                    type: 'category',
                    label: 'Essential Resources',
                    items: [
                        {
                            type: 'doc',
                            id: 'general-hackerpack',
                            label: 'Hackerpack',
                        },
                        {
                            type: 'doc',
                            id: 'devpost-guide',
                            label: 'Devpost Guide',
                        },
                    ],
                },
                // Team Resources (renamed from "Other Information")
                {
                    type: 'category',
                    label: 'Other Resources',
                    items: [
                        {
                            type: 'doc',
                            id: 'travel-guide',
                            label: 'Travel Guide',
                        },
                        {
                            type: 'doc',
                            id: 'mentor-guide',
                            label: 'Need a Mentor?',
                        },
                        {
                            type: 'doc',
                            id: 'judge-guide',
                            label: 'Submission & Judging Guide',
                        },
                        {
                            type: 'doc',
                            id: 'travel-reimbursement',
                            label: 'Travel Reimbursement',
                        }
                    ],
                },
                // Guided Project as its own top-level category
                {
                    type: 'category',
                    label: 'Guided Project',
                    link: {
                        type: 'doc',
                        id: 'Guided Project/index',
                    },
                    items: [
                        {
                            type: 'category',
                            label: 'All Resources',
                            link: {
                                type: 'doc',
                                id: 'Guided Project/All Resources/index',
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'Guided Project/All Resources',
                                },
                            ],
                        },
                        {
                            type: 'doc',
                            id: 'Guided Project/Installation_Guide',
                            label: 'Installation Guide',
                        },
                        {
                            type: 'category',
                            label: 'Frontend',
                            link: {
                                type: 'doc',
                                id: 'Guided Project/Frontend/index',
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'Guided Project/Frontend',
                                },
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Backend',
                            link: {
                                type: 'doc',
                                id: 'Guided Project/Backend/index',
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'Guided Project/Backend',
                                },
                            ],
                        },
                        {
                            type: 'doc',
                            id: 'Guided Project/Bonus',
                            label: 'Bonus',
                        },
                    ],
                },
                // Event Information
                {
                    type: 'category',
                    label: 'Event Logistics',
                    items: [
                        {
                            type: 'doc',
                            id: 'venue-parking',
                            label: 'Venue & Parking',
                        },
                        {
                            type: 'doc',
                            id: 'prizes-challenges',
                            label: 'Prizes & Challenges',
                        },
                    ],
                },
            ],
        },
    ],
};
